---
- hosts: web
sudo: true
tasks:
- name: Create JDK Application Directory
command: mkdir -p /opt/AIC-CLOUDS/
- name: Create Devlopment Directory
command : mkdir /opt/router-package
- name: Copy the JDK TAR file
copy: src=/opt/AIC-CLOUDS/router-package/jdk-7-linux-i586.tar.gz dest=/opt/router-package/jdk-7-linux-i586.tar.gz
- name: Extract archive
unarchive: src=/opt/router-package/jdk-7-linux-i586.tar.gz dest=/opt/router-package/ copy=no
- name: Rename Directory
command: mv /opt/router-package/jdk1.7.0 /opt/AIC-CLOUDS/jdk1.7.0
- name: Install Java
command: update-alternatives --install /usr/bin/java java /opt/AIC-CLOUDS/jdk1.7.0/bin/java 2
- name: Install Jar
command: update-alternatives --install /usr/bin/jar jar /opt/AIC-CLOUDS/jdk1.7.0/bin/jar 2
- name: Install javac
command: update-alternatives --install /usr/bin/javac javac /opt/AIC-CLOUDS/jdk1.7.0/bin/javac 2
- name: Set Jar
command: update-alternatives --set jar /opt/AIC-CLOUDS/jdk1.7.0/bin/jar
- name: Set Javac
command: update-alternatives --set javac /opt/AIC-CLOUDS/jdk1.7.0/bin/javac
- name: Set first line at EOF (1/3)
lineinfile: dest=/etc/profile regexp="^string 1" line="JAVA_HOME=/opt/AIC-CLOUDS/jdk1.7.0/"
- name: Set second line after first (2/3)
lineinfile: dest=/etc/profile regexp="^string 2" line="export JAVA_HOME" insertafter="^JAVA_HOME=/opt/AIC-CLOUDS/jdk1.7.0/"
- name: Set third line after second (3/3)
lineinfile: dest=/etc/profile regexp="^string 3" line="PATH=$JAVA_HOME/bin:$PATH" insertafter="^export JAVA_HOME"
- name: Set 4th Line
lineinfile: dest=/etc/profile regexp="^string 4" line="export PATH" insertafter="^PATH=$JAVA_HOME/bin:$PATH"

- name: Create TOMCAT Application Directory
command: mkdir -p /opt/AIC-CLOUDS/tomcat
- name: Copy the TOMCAT TAR file
copy: src=/opt/AIC-CLOUDS/router-package/apache-tomcat-7.0.47.tar.gz dest=/opt/router-package/apache-tomcat-7.0.47.tar.gz
- name: untar APACHE TOMCAT
shell: tar xzvf /opt/router-package/apache-tomcat-7.0.47.tar.gz --strip 1 -C /opt/AIC-CLOUDS/tomcat
- name: change port no 1
command: sed -i 's#8080#9090#' /opt/AIC-CLOUDS/tomcat/conf/server.xml
- name: change port no 2
command: sed -i 's#8005#9005#' /opt/AIC-CLOUDS/tomcat/conf/server.xml
- name: set line 36
command: sed -i '36 i\<role rolename="manager-gui"/>' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: set line 37
command: sed -i '37 i\<role rolename="manager-script"/>' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: set line 38
command: sed -i '39 i\<role rolename="manager-status"/>' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: set line 39
command: sed -i '39 i\<role rolename="manager-status"/>' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: set line 40
command: sed -i '40 i\<role rolename="admin-gui"/> ' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: set line 41
command: sed -i '41 i\<role rolename="admin-script"/>' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: set line 42
command: sed -i '42 i\<user username="tomcat" password="password" roles="manager-gui,manager-script,manager-jmx,manager-status,admin-gui,admin-script"/>' /opt/AIC-CLOUDS/tomcat/conf/tomcat-users.xml
- name: copy tom
copy: src=/etc/ansible/tomc.sh dest=/opt/router-package/tomc.sh
- name: start service
command: bash /opt/router-package/tomc.sh
