version: '2'
services:
    gateone:
        image: arush/gateone:http
        ports:
            - "8080:8000"
        hostname: kubectl
        networks:
            - frontend
        volumes:
            - ssh_key:/root/.ssh/
            - /opt/kubernetes-clusters/cka/gateone/config:/root/kubeconfig
    lab:
        image: arush/cka_lab
        ports:
            - "80:80"
        networks:
            - frontend
networks:
    frontend: {}
volumes:
    ssh_key: {}
