apiVersion: v1
kind: Secret
metadata:
  name: demo-sa-secret
  annotations:
    # This will map the Secret to "custom-sa" Service Account
    kubernetes.io/service-account.name: custom-sa
# This will create Token for the Service Account "custom-sa"
type: kubernetes.io/service-account-token
