---
####DEPENDENCY INSTALLATION
- name: DEPENDENCY INSTALLATION
  apt: name={{item}} state=installed
  with_items:
       - net-tools
       - netcat
       - python-software-properties
       - apt-transport-https
       - curl
####java installation######
- name: ADD JAVA 8 REPOSITORIES
  apt_repository: repo='ppa:webupd8team/java'
- name: INSTALL JAVA
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
- name: Install Java 8
  apt: name=oracle-java8-installer force=yes

- name: Add Jenkins apt repository key
  apt_key:
    url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
    state: present

- apt_repository:
    repo: deb https://pkg.jenkins.io/debian-stable binary/
    state: present

- name: apt-get update
  apt:
    update-cache: yes

#- name: install jenkins
#  apt:
#    name: jenkins
#    state: present
#    update_cache: yes


- name: copy jenkins specific version deb file
  copy:
    src: /etc/ansible/softs/jenkins_2.142_all.deb 
    dest: /tmp/jenkins_2.142_all.deb


- name: Install our specific version of Jenkins.
  apt:
    deb: /tmp/jenkins_2.142_all.deb
    state: present

#- name: Download maven
#  get_url:
#    url: http://www-eu.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
#    dest: /tmp/apache-maven-3.3.9-bin.tar.gz
#
#- name: extract maven
#  unarchive:
#    src: apache-maven-3.3.9-bin.tar.gz
#    dest: /opt/apps/softs
#
#- name: rename directory 
#  shell: mv /opt/apps/softs/apache-maven-3.3.9 /opt/apps/maven
#
#
#- name: copy maven file
#  copy:
#    src: /etc/ansible/files/mavenenv.sh
#    dest: /etc/profile.d/mavenenv.sh
#    mode: 777
#
#- name: map maven path
#  shell: . /etc/profile.d/mavenenv.sh
#  become: true
#  become-user: root


#  args:
#    executable: /bin/bash
#
#- name: verify maven version
#  shell: mvn --version
#  become: true
#  become-user: root

















