- hosts: all
  become_user: root
  become: yes
  tasks:
    - name: Making solr logs dir and change ownership
      file:
        path: /opt/data/solr/logs
        state: directory
        owner: solr
        group: solr
        recurse: yes

    - name: Making zookeeper logs dir and change ownership
      file:
        path: /opt/data/zookeeper/logs
        state: directory
        owner: solr
        group: solr
        recurse: yes

    - name: Updating logs dir path in solr.in.sh
      lineinfile:
        path: /opt/apps/solr/bin/solr.in.sh
        regexp: 'SOLR_LOGS_DIR='
        line: 'SOLR_LOGS_DIR="/opt/data/solr/logs"'

    - name: Updating log dir path in zookeeper-env.sh
      lineinfile:
        path: /opt/apps/zookeeper/conf/zookeeper-env.sh
        regexp: 'export ZOO_LOG_DIR="'
        line: 'export ZOO_LOG_DIR="/opt/data/zookeeper/logs"'

    - name: Updating log dir path in log4j.properties
      lineinfile:
        path: /opt/apps/solr/server/resources/log4j.properties
        regexp: 'solr.log='
        line: 'solr.log=/opt/data/solr/logs'

    - name: Updating the crontab for solr log-sync
      replace:
        path: /var/spool/cron/crontabs/ubuntu
        regexp: '^(.+)\/opt\/apps\/solr\/server\/logs(.+)$'
        replace: '\1/opt/data/solr/logs\2'

    - name: Restarting Cron
      service:
        name: cron
        state: restarted

    - name: Restarting Zookeeper
      service:
        name: zookeeper
        state: restarted

    - name: Restarting Solr
      shell: /etc/init.d/solr restart warn=False # Using Service module for solr is insufficient

