---
- name: OVERWRITE MY ID FILE
  template:
    src: myid.j2
    dest: "{{ zookeeper_data_dir }}/myid"
    force: "{{ zookeeper_force_myid }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper
- name: OVERWRITE DEFAULT CONFIG FILE
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_conf_dir }}/zoo.cfg"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper

#- name: Restart zookeeper
#  command: /opt/app/zookeeper/bin/zkServer.sh start
