---
- name: Test Playbook
  hosts: dev
  become: yes
  become_user: root
  become_method: su 
  vars:
    tmpdata: "{{ lookup('file','/opt/m2.json')|from_json }}"  

  tasks:
    - name: testing module
      execute_command: command="cat /opt/metrics.json | grep -i ss311350-1 | sed -n '1p' | awk '{print $2;}' | sed 's/..$//;s/^.//'"
      #execute_command: command="cat /opt/metrics.json | grep -i ss311350-1"
      #execute_command: command="cat /tmp/metrics.json"
      #execute_command: command="find ."
      #execute_command: command="ps -ef | grep nginx"
      register:  data
  
    - debug:
        var: data
    #- debug: msg="{{ data|from_json|attr('data') }}"   
    #- set_fact: myvar="{{ data.stdout | from_json }}"
    #- debug: 
    #    var: "{{ data.result }}"
    
    - shell: cat /opt/j.json
      register: result

#    - set_fact:
#        msg: "{{ result.stdout | from_json }}"
    - name: json data
      debug: var=result
      #debug: var= {{ result.stdout | from_json }}

    - name: print  j
      command: cat /opt/m
      register: result2

    - name: json data
      debug: var=result2

    - name: Iterate JSON
      debug: var=item.contextRoot
      with_items: "{{ tmpdata.hosts }}"

    - name: Iterate JSON2
      set_fact:
        app_item: "{{ item.node }}"
      with_items: "{{ tmpdata.hosts }}"
      register: app_result

    - name: Create Fact List
      set_fact:
          apps: "{{ app_result.results | map(attribute='ansible_facts.app_item') | list }}"

    - name:  Print Fact
      debug: var=apps   
   
    - name: "Read daemon.json"
      command: cat /opt/metrics.json
      register: result3
      changed_when: no
    - set_fact: docker_daemon_json="{{ result3.stdout | from_json }}"
   
