- hosts: dev
  connection: local
  tasks:
     - name: Create a k8s namespace
       k8s:
         name: testing
         api_version: v1
         kind: Namespace
         state: present
     - name: create nginx deploy
       k8s:
         state: present
         definition: "{{ lookup('template', 'files/nginx-deploy.yml.j2') }}"
     - name: create nginx svc
       k8s:
         state: present
         definition: "{{ lookup('template', 'files/nginx-svc.yml.j2') }}"
     - name: Get the details of the nginx Service.
       k8s_info:
         api_version: v1
         kind: Service
         name: nginx
         namespace: testing
       register: nginx_svc

     - name: Print the NodePort of the nginx Service.
       debug:
         var: nginx_svc.resources[0].spec.ports[0].nodePort
