apiVersion: v1
kind: Pod
metadata:
  name: node-affinity
  labels:
    k8s-app: node-affinity
spec:
  containers:
  - name: busybox
    image: busybox:1
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    volumeMounts:
    - name: data
      mountPath: /data
    securityContext:
      runAsUser: 10000
    command: ["/bin/sh"]
    args:
    - -c
    - sleep 10800
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: role
            operator: In
            values: ["app"] 
  volumes:
  - name: data
    emptyDir: {}
