apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-with-error-
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: busybox
        image: busybox:1
        command:
        - sh
        - -c
        - "sleep 2 && exit 1"
      restartPolicy: Never
