apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-httpd
  labels:
    k8s-app: statefulset-httpd
spec:
  serviceName: "http-service"
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-container
        image: httpd
        volumeMounts:
        - name: data
          mountPath: /usr/loca/apache2/htdocs
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: fast
      accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 1Gi
