apiVersion: v1
kind: Pod
metadata:
  name: qos-guranteed
  labels:
    k9s-app: qos-guranteed
spec:
  containers:
  - name: nginx-qos-guranteed
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
