apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable-multi-container
  labels:
    k8s-app: qos-burstable-multi-container
spec:
  containers:
  - name: nginx-qos-burstable
    image: nginx
    resources:
      requests:
        memory: 100Mi
  - name: redis-qos-burstable
    image: redis
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
