apiVersion: v1
kind: Pod
metadata:
  name: qos-burstable
  labels:
    k9s-app: qos-burstable
spec:
  containers:
  - name: nginx-qos-burstable
    image: nginx
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 50m
        memory: 100Mi
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
