apiVersion: v1
kind: Pod
metadata:
  name: qos-best-effort
  labels:
    k9s-app: qos-bestEffort
spec:
  containers:
  - name: nginx-qos-best-effort
    image: nginx
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
