apiVersion: v1
kind: Pod
metadata:
  name: downword-api
  labels:
    k8s-app: downwordApi-demo
    zone: dc5
  annotations:
    build: master
    buulder: Bhavesh
spec:
  containers:
  - name: busybox-container
    image: busybox:1
    command:
    - /bin/sh
    - -c
    - sleep 8600;
    resources:
      limits:
        cpu: 150m
        memory: 100Mi
      requests:
        cpu: 150m
        memory: 100Mi
    volumeMounts:
    - name: downwordapi-data
      mountPath: /mnt/api-data
      readOnly: false
  volumes:
  - name: downwordapi-data
    downwardAPI:
      items:
        - path: "labels"
          fieldRef: 
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
