apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    k8s-app: secret-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep","8600"]
    volumeMounts:
    - name: data
      mountPath: /mnt/data
  volumes:
  - name: data
    secret:
      secretName: secret-data
