apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
  labels:
    k8s-app: secret-env-pod
spec:
  containers:
  - name: container
    image: busybox:1
    env:
    - name: SECRET_USER
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: user
    - name: SECRET_PASS
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: pass
    command: ["sleep","8600"]
