---
- name:  apt update
  apt: update_cache=true  cache_valid_time=3600


- name: install required packages
  apt: name={{ item }} state=present
  with_items:
    - nginx

- name: Configuring ngnix port
  template: src=default dest=/etc/nginx/sites-available
  notify:
    - restart nginx

#- name: restart nginx
#  service: name=nginx state=restarted



- name: create htpasswd
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ name }}"
    password: "{{ password }}"
#    group: nginx
    mode: 0640
  become: true
  notify:
    - restart nginx

