---
- hosts: dev
  become: yes
  become_method: sudo
  become_user: deploy

  serial: 
    - 1
    - 2
    - 50%
  tasks:
  - name: copy sample.txt
    copy:
      src: /tmp/sample.txt
      dest: /tmp/
      mode: 0775
