---
[sandbox]
ac1 ansible_ssh_host=xxxxxx ansible_ssh_user=xxxxx


[dev]
ac1 ansible_ssh_host=xxxxxxx ansible_ssh_user=xxxxx ansible_ssh_pass=xxxxx


[dev]
lc ansible_ssh_host=127.0.0.1 ansible_ssh_user=root ansible_ssh_private_key_file=~/.ssh/id_rsa

ansible_python_interpreter=/usr/local/bin/python2.7



