---
- hosts: web
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: install apache
    yum: name=httpd state=latest
  - name: start and enable apache
    service: name=httpd state=started enabled=yes
  - name: retrieve website
    get_url: url=http://repo.example.com/website.tgz dest=/tmp/website.tgz
  - name: install web
    unarchive: remote_src=yes src=/tmp/website.tgz dest=/var/www/html/

