apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-demo
  namespace: demo-dp
  labels:
    k8s-app: apache-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache-container
        image: httpd
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 200Mi
