apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-pod
  labels:
    k8s-app: emptydir-volume-pod
spec:
  containers:
  - name: emptydir-volume-nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
  restartPolicy: Always
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  volumes:
  - name: nginx-storage
    emptyDir: {}
