apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  # 'raw' for raw block device or 'filesystem' (default)  
  volumeMode: Filesystem
  # It can be 'ReadWriteOnce', 'ReadOnlyMany', or 'ReadWriteMany'
  accessModes:
  - ReadWriteOnce
  # It can be 'Retain', 'Recycle', 'Delete'
  persistentVolumeReclaimPolicy: Recycle
  # using 'hostPath' volume
  hostPath:
    path: "/mnt/data"
