apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gid
  labels:
    type: local-pv-gid
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: pv-class
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data-gid
