apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gid
  labels:
    type: local-gid
spec:
  storageClassName: pv-class
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
