apiVersion: v1
kind: Pod
metadata:
  name: projected-volume-pod
  labels:
    k8s-app: projected-volume-pod
spec:
  containers:
  - name: busybox
    image: busybox
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 200m
        memory: 500Mi
    imagePullPolicy: Always
    command: ["sleep"]
    args: ["10800"]
    volumeMounts:
    - name: all-in-one
      mountPath: /projected-volume
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: user
      - secret:
          name: pass
