apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pvc
  labels:
    k8s-app: ubuntu-pvc
spec:
  containers:
  - name: ubuntu-contianer
    image: ubuntu
    command: ["sleep"]
    args: ["10800"]
    volumeMounts:
    - name: volume-gid 
      mountPath: /data
  restartPolicy: Always
  volumes:
  - name: volume-gid
    persistentVolumeClaim:
      claimName: pvc-gid 
