apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
  labels:
    k8s-app: pvc-pod
spec:
  containers:
  - name: pvc-nginx
    image: nginx
    volumeMounts:
    - name: nginx-storage
      mountPath: /usr/share/nginx/html
  restartPolicy: Always
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  volumes:
  - name: nginx-storage
    persistentVolumeClaim:
      claimName: pvc-volume 
