apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dp
  labels:
    k8s-app: httpd-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: http-container
        image: httpd
        imagePullPolicy: Always
