---
- name: reload-systemd
  systemd:
    daemon_reload: yes

- name: start ha
  systemd:
     state: started
     name: haproxy    

- name: stop ha
  systemd:
     state: started
     name: haproxy


- name: restart ha
  systemd:
     state: restarted
     name: haproxy


- name: restart keep
  systemd:
     state: restarted
     name: keepalived

- name: restart net
  systemd:
     state: restarted
     name: network
     
