apiVersion: v1
kind: Pod
metadata:
  name: cpu-limit
  labels:
    k8s-app: cpu-limit
spec:
  containers:
  - name: cpu-limit-container
    image: vish/stress
    resources:
      limits:
        cpu: 1
      requests:
        cpu: 0.5
    args: ["-cpus","2"]
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
