apiVersion: v1
kind: Pod
metadata:
  name: cpu-high
  labels:
    k8s-app: cpu-high
spec:
  containers:
  - name: cpu-high-container
    image: vish/stress
    resources:
      limits:
        cpu: 10
      requests:
        cpu: 10
    args: ["-cpus","2"]
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
