apiVersion: v1
kind: Pod
metadata:
  name: high-mem
  labels:
    k9s-app: high-mem
spec:
  containers:
  - name: high-mem
    image: polinux/stress
    resources:
      limits:
        memory: 500Gi
      requests:
        memory: 500Gi
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
  tolerations:
  - key: node-role.kubernetes.io/master 
    effect: NoSchedule
    operator: Exists
