# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v sudo apt-get) ]; then sudo apt-get update ; fi

CMD ["/usr/bin/java", "-Djenkins.install.runSetupWizard=false", "-jar","/usr/share/jenkins/jenkins.war"]
