---

####DEPENDENCY INSTALLATION

- name: DEPENDENCY INSTALLATION
  apt: name={{item}} state=installed
  with_items:
       - net-tools
       - netcat
       - python-software-properties





####java installation######

- name: ADD JAVA 8 REPOSITORIES
  apt_repository: repo='ppa:webupd8team/java'

- name: INSTALL JAVA
  debconf: name=oracle-java8-installer question=shared/accepted-oracle-license-v1-1 vtype=select value=true
- name: Install Java 8
  apt: name=oracle-java8-installer force=yes



#####ZOOKEEPER PATH CREATION

- name: ZOOKEEPER PATH CREATION
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  with_items:
    - "{{ zookeeper_install_path }}"
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_data_dir }}"
    - "{{ zookeeper_log_dir }}"


###ZOOKEEEPER TAR BALL DOWNLOAD
- name: ZOOKEEEPER TAR BALL DOWNLOAD
  get_url: url={{zookeeper_url}} dest={{zookeeper_tarball_dir}}/zookeeper-{{zookeeper_version}}.tar.gz
  tags: bootstrap
  register: zookeeper_tarball_downloaded

###ZOOKEEPER TAR BALL EXTRACTION

- name: ZOOKEEPER TAR BALL EXTRACTION
  command: tar xf {{zookeeper_tarball_dir}}/zookeeper-{{zookeeper_version}}.tar.gz --strip-components=1 chdir={{zookeeper_dir}} creates={{zookeeper_dir}}/bin
  tags: bootstrap

- group: name=zookeeper system=yes
- user: name=zookeeper group=zookeeper system=yes

- name: CHANGE OWNERSHIP ON ZOOKEEPER DIRECTORY
  file: path={{zookeeper_dir}} state=directory owner=zookeeper group=zookeeper
  tags: bootstrap

#### ZOOKEEPER DIRECTORY CREATION

- name: ZOOKEEPER DIRECTORY CREATION
  file: path={{item}} state=directory owner=zookeeper group=zookeeper
  tags: bootstrap
  with_items:
    - "{{zookeeper_data_dir}}"
    - "{{zookeeper_log_dir}}"
####ZOOKEEPER SYSTEMD SERVICE CREATION

- name: ZOOKEEPER  SERVICE CREATION
  template:
    src: zookeeper.j2
    dest: /etc/init.d/zookeeper
#  notify:
#    - Restart zookeeper






