[localnode]
local  ansible_ssh_host=127.0.0.1  ansible_ssh_user=ansible ansible_ssh_pass=zmHtnoIHRQ
[web]
node1  ansible_ssh_host=10.0.1.221  ansible_ssh_user=ansible ansible_ssh_pass=zmHtnoIHRQ
[database]
node2  ansible_ssh_host=10.0.1.49   ansible_ssh_user=ansible ansible_ssh_pass=zmHtnoIHRQ

