apiVersion: v1
kind: Pod
metadata:
  name: pod-security-context
  labels:
    k8s-app: pod-security-context
spec:
  containers:
  - name: node-hello
    image: gcr.io/google-samples/node-hello:1.0
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 100Mi
    imagePullPolicy: Always
    volumeMounts:
    - name: emptydir
      mountPath: /data
    securityContext:
      allowPrivilegeEscalation: false
  restartPolicy: Always
  volumes:
  - name: emptydir
    emptyDir: {}
  securityContext:
    runAsUser: 1000
    supplementalGroups: [1000]
    fsGroup: 2000
