apiVersion: v1
kind: Pod
metadata:
  name: security-context-capability
  labels:
    k8s-app: security-context-capability
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi
    command: ["sleep"]
    args: ["10800"]
    volumeMounts:
    - name: data
      mountPath: /data
    imagePullPolicy: Always
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
  volumes:
  - name: data
    emptyDir: {}
