---
jenkins_repo_url: deb https://pkg.jenkins.io/debian-stable binary/
jenkins_repo_key_url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
jenkins_pkg_url: https://pkg.jenkins.io/debian/binary
jenkins_init_file: /etc/default/jenkins
jenkins_http_port_param: HTTP_PORT
jenkins_java_options_env_var: JAVA_ARGS


#https://pkg.jenkins.io/debian/jenkins-ci.org.key
