apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  labels:
    k8s-app: my-secret
  annotations:
    version: task8
type: Opaque
data:
  username: YWRtaW4K 
  password: V29XCg== 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-env-secretref
  labels:
    k8s-app: dp-env-secretref
  annotations:
    version: task8
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers: 
      - name: busybox
        image: busybox
        imagePullPolicy: IfNotPresent
        command:
        - printenv
        resources:
          requests:
            cpu: 200m
        env:
        - name: REQUEST_CPU
          valueFrom:
            resourceFieldRef:
              containerName: busybox
              resource: requests.cpu
        - name: MY_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: MY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
      restartPolicy: Always
