apiVersion: batch/v1
kind: Job
metadata:
  name: job-busybox
  labels:
    k8s-app: job-busybox
  annotations:
    version: task11
spec:
  completions: 5
  parallelism: 2
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: container-busybox
        image: busybox
        imagePullPolicy: Always
        command:
        - /bin/sh
        - -c
        - |
          touch /tmp/loop
          while test -e "/tmp/loop";
            do
              for i in 1 3 5 7 9 11; do echo $i && sleep 1; done
          done
      restartPolicy: OnFailure
