apiVersion: v1
kind: ResourceQuota
metadata:
  name: ns-quota
  labels:
    k8s-app: ns-quota
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: 4096Mi
    limits.cpu: "2000m"
    limits.memory: 4096Mi
    pods: "5"
    secrets: "5"
    #replicationControllers: "1"
    #deployment: "5"
    #configmap: "3"
