apiVersion: v1
kind: LimitRange
metadata:
  name: ns-limit
  labels:
    k8s-app: ns-limit
spec:
  limits:
  - type: Container
    default:
      cpu: 100m
      memory: 100Mi
    defaultRequest:
      cpu: 100m
      memory: 100Mi
    min:
      cpu: 100m
      memory: 100Mi
    max:
      cpu: 2000m
      memory: 4096Mi
  - type: PersistentVolumeClaim
    min:
      storage: 1Gi
    max:
      storage: 100Gi
    
    
