---
- hosts: qa
  remote_user: root
  become: true
  become_method: sudo
  tasks:
    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 0412F522
    - apt_repository:
        repo: deb http://repo.openbytes.ie/ubuntu trusty main
        state: present

    - name: apt-get update
      apt:
        update-cache: yes

    - name: install patchman-client
      apt: name=patchman-client  update_cache=yes state=latest
      register: out1
    - debug: var=out1.stdout_lines

