---
#- name: Restart jenkins now
#  service: name=jenkins state=restarted
#  when: config_changed.changed
- name: start jenkins
  systemd:
    name: jenkins
    state: started
- name: Creates groovy directory
  file: path=/var/lib/jenkins/init.groovy.d state=directory
- name: copy basic-security-groovy script
  copy:
    src: /etc/ansible/roles/nik-jenkins-1/templates/basic-security.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
#- name: sleep for 30 seconds and continue with play
#  wait_for: timeout=30
#  delegate_to: localhost

#- name: init password jenkin
#  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#  changed_when: false
#  register: result

#- name: print init password jenkins
#  debug:
#    var: result.stdout
