# Molecule managed

---
all:
  hosts:
    instance: &id001
      ansible_host: 127.0.0.1
      ansible_port: '2222'
      ansible_private_key_file: /home/controller/Desktop/controller-repo/vagrant-repo/molecule/mol-vag/zookeeper/molecule/default/.molecule/.vagrant/machines/instance/virtualbox/private_key
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o ControlMaster=auto
        -o ControlPersist=60s -o IdentitiesOnly=yes -o StrictHostKeyChecking=no
      ansible_user: vagrant
      connection: ssh
ungrouped:
  hosts:
    instance: *id001
  vars: {}
