---
#- name: Pull the latest official jenkins docker image
#  docker_image:
#    name: "jenkins:latest"
#- name: Create a container from the jenkins docker image
#  docker_container:
#    name: "jenkins-server"
#    image: "jenkins"
#    ports:
#        - "8080:8080"
#        - "50000:50000"
#    volumes:
#        - "/share/jenkins:/var/jenkins_home"
#    state: present
#    recreate: no
- name: run docker jenkins container
  shell: docker run --name dev-jen-4  -p 8080:8080 -v /opt/apps/jenkins-data:/var/jenkins_home -v /opt/apps/maven:/opt/maven   -d -e JAVA_OPTS="-Djenkins.install.runSetupWizard=false" zlid/jenkins-sudo

- name: copy basic-security-groovy script
  copy:
    src: /etc/ansible/roles/nik-jenkins-2/templates/basic-security.groovy.j2
    dest: /opt/apps/jenkins-data/init.groovy.d/basic-security.groovy
- name: copy blueocean plugins list
  copy:
    src: /etc/ansible/files/p4.yml
    dest: /opt/apps/plugs/p4.yml
    mode: 777
- name: copy blueocean install script
  copy:
    src: /etc/ansible/files/jenkinscool.py
    dest: /opt/apps/plugs/jenkinscool.py
    mode: 777

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    user: "admin"
    password: "admin"
    timeout: 5
    force_basic_auth: yes
  register: jenkins_service_status
  retries: 10
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200
- name: Check Jenkins status
  debug:
    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"


- name: Install plugin
  jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: admin
    url: http://localhost:8080
  with_items: "{{ plugins }}"
  #with_items: build-pipeline-plugin

- name: execute blueocean install script
  shell: python /opt/apps/plugs/jenkinscool.py -i /opt/apps/plugs/p4.yml



- name: upgradation of jenkins.war
  shell: docker cp /opt/apps/jenkins-wars/jenkins.war dev-jen-4:/usr/share/jenkins/jenkins.war

- name: restart of jenkins
  shell: java -jar /opt/apps/jenkins-wars/jenkins-cli.jar -s http://192.168.10.25:8080/ restart --username admin --password admin


