---
- name: copy blueocean plugins list
  copy:
    src: /etc/ansible/files/p5.yml
    dest: /opt/apps/plugs/p5.yml
    mode: 777


- name: copy blueocean install script
  copy:
    src: /etc/ansible/files/jenkinscool.py
    dest: /opt/apps/plugs/jenkinscool.py
    mode: 777


#- name: execute blueocean install script
#  shell: python /opt/apps/plugs/jenkinscool.py -i /opt/apps/plugs/p5.yml







#- name: Install plugin
#  jenkins_plugin:
#    name: "{{ item }}"
   # url_username: admin
   # url_password: admin
   # url: http://127.0.0.1:8080
  #with_items: "{{ plugins }}"
#  with_items: build-pipeline-plugin



#- name: Wait for Jenkins to start up
#  uri:
#    url: http://172.17.0.2:8080
#    status_code: 200
#    user: admin
#    password: admin
#    timeout: 5
#    force_basic_auth: yes
#  register: jenkins_service_status
#  retries: 3
#  delay: 2
#  until: >
#     'status' in jenkins_service_status and
#     jenkins_service_status['status'] == 200
#- name: Check Jenkins status
#  debug:
#    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"
#
#
#- name: Install Jenkins plugins
#  jenkins_plugin:
#    name: "{{ item }}"
#    url: http://172.17.0.2:8080
#    url_username: admin
#    url_password: admin
#    state: present
#  with_items:
#    - build-pipeline-plugin
#  when: jenkins_service_status['status'] == 200
#
