require 'rake'
require 'rspec/core/rake_task'
require 'yaml'
require 'mongo'

Mongo::Logger.logger.level = ::Logger::FATAL
client = Mongo::Client.new([ '127.0.0.1:27017' ], :database => 'inventory', :user => 'sys', :password => 'iis123')


properties = YAML.load_file('properties.yml')
#ansible_properties = YAML.load_file('vagrant-inventory1.yml')


desc "Run serverspec to all hosts"
task :spec => 'serverspec:all'

namespace :serverspec do
  task :all => properties.keys.map {|key| 'serverspec:' + key.split('.')[0] }
  properties.keys.each do |key|
    desc "Run serverspec to #{key}"
    RSpec::Core::RakeTask.new(key.split('.')[0].to_sym) do |t|
      ENV['TARGET_HOST'] = key
      ENV['TARGET_USER'] = 'root'
      #ENV['TARGET_IPV4'] = ansible_properties[key]['ansible_ssh_host']
      #client[:awsnodes].find().each{ |doc| puts doc['hostvars'].select{|a| a['value']['host_var'] == key}[0]['id'] }
      #client[:awsnodes].find().each{ |doc| ENV['TARGET_IPV4'] = doc['hostvars'].select{|a| a['value']['host_var'] == key}[0]['id'] }
      client[:awsnodes3].find().map{ |doc| doc['_meta']['hostvars'] }.map{ |a| [a.keys, a.values] }.each do |k,v| 
	 h = k.zip v
	 h.select{|h1,h2| h2['host_var'] == key }.each{|h1,h2| ENV['TARGET_IPV4'] = h1}	 
      end
      t.pattern = 'spec/{' + properties[key][:roles].join(',') + '}/*_spec.rb'
    end
  end
end
