---

- hosts: zookeeper
  pre_tasks:
    - name: installing required libs
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - netcat
    - name: remove localhost from hosts
      lineinfile:
        path: /etc/hosts
        regexp: '127\.0\.1\.1.*{{inventory_hostname}}.*{{inventory_hostname}}'
        state: absent
        owner: root
        group: root
        mode: 0644

- hosts: zookeeper
  roles:
    - nik-zookeeper
