- hosts: dev
  become: yes
  become_user: jenkins
  become_method: sudo
  tasks:
      - name: print hello
        shell: echo "hello world" 
        register: helo

      - name: Print helo
        debug:
          msg: "helo output: {{ helo.stdout }}"
          
      - name: Print mosh version
        debug: "msg=helo: '{{ helo.stdout }}'"    
