---
- hosts: dev
  become: true
  #become_user: deploy
  #become_method: sudo


  tasks:
    - name: Running API
      uri:
        url: https://api.github.com/users
        method: GET
        return_content: yes
      register: user_list

    - name: App Details
      debug: var=user_list
    



