- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - name: Read disks and mount points
        debug:
          msg: "Device: {{ item.device }} Mount Point: {{ item.mount }}"
        with_items: "{{ ansible_mounts }}"
        loop_control:
          label: "{{item.mount}}"

      - name: Find solr log4j path
        shell: cat /opt/apps/solr/server/resources/log4j.properties | grep -i solr.log | sed -n '1p' | cut -d "="  -f2
        register: solr_log4j_path

      - name: Print solr log4j path
        debug:
          msg: "Solr log4j path: {{ solr_log4j_path.stdout }}"

      - name: Find solr log dir path
        shell: cat /opt/apps/solr/bin/solr.in.sh | grep -i SOLR_LOGS_DIR= | cut -d "=" -f2 | sed 's/.$//; s/^.//'
        register: solr_log_path

      - name: Print solr logs dir path
        debug:
          msg: "Solr logs path: {{ solr_log_path.stdout }}"

      - name: Find zookeeper log dir path
        shell: cat /opt/apps/zookeeper/conf/zookeeper-env.sh  | grep -i ZOO_LOG_DIR= | sed -n '2p' | cut -d "="  -f2 |  sed 's/.$//; s/^.//'
        register: zookeeper_log_path

      - name: Print zookeeper log dir path
        debug:
          msg: "Zookeeper log path: {{ zookeeper_log_path.stdout }}"
