- hosts: dev
  become: yes
  become_user: root
  become_method: sudo
  tasks:
      - pip:
          requirements: /etc/ansible/requirements.txt
      - name: execute python script
        command: python /etc/ansible/rest.py
        register: rest
      - name: print output
        debug:
          msg: "rest api output: {{ rest.stdout }}"
