- hosts: dev
  tasks:
     - name: Deploy war file
       get_url:
         url: https://s3.amazonaws.com/hello-artifactory/2019-05-11-20-05/mavenproject1-1.0-SNAPSHOT.war
         dest: /opt/apps/tomcat/webapps
         mode: 0775
