- hosts: local
  tasks:
     - name: Deploy war file
       get_url:
         url: "https://s3.amazonaws.com/hello-artifactory/{{ build_no }}/{{ ear_ver }}"
         dest: /opt/apps/tomcat/webapps
         mode: 0775
