apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-demo
spec:
  containers:
  - name: lifecycle-demo-container
    image: nginx
    lifecycle:
      # Handler: set environment before container entrypoint, but there is no gurantee that entrypoint will start after this handler.
      postStart:
        exec:
          command: ["/bin/sh","-c","echo Hello from Nginx!!! > /usr/share/nginx/html/welcome.html"]
      # Handler: Clean up after Container Termination
      preStop:
        exec:
          command: ["/usr/sbin/nginx","-s","quit"]
