---
- name: DEMO AN INTERACTIVE PRIVATE KEY
  hosts: dev
  become: true
  remote_user: deploy
  gather_facts: no
  tasks:

    - name: DISPLAY THE INJECTED EXTRA VAR
      debug:
        var: secret_key

    - name: CLONE THE GIT REPO
      git:
        repo: git@github.com:nik786/hello-tomcat-project-2.git
        dest: /tmp/test-git
        key_file: "{{ secret_key  }}"
      

