---
- hosts: dev
  become: yes
  become_method: sudo
  become_user: deploy

  tasks:
      - name: print hello
        shell: echo "hello world" 
        register: helo
      - name: Print helo
        debug:
          msg: "helo output: {{ helo.stdout }}"
