---
- name: apt update
  apt: update_cache=true  cache_valid_time=3600


- name: install required packages
  apt: name={{ item }} state=present
  with_items:
    - nginx
    - python-pip

- name: Installing python-passlib
  pip: name=passlib
- name: Configuring ngnix port
  template: src=default dest=/etc/nginx/sites-available
#  notify:
#    - start nginx
- name: create htpasswd
  htpasswd:
    path: /etc/nginx/.htpasswd
    name: "{{ uname }}"
    password: "{{ upassword }}"
#    group: nginx
    mode: 0640
  become: true
