apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  storageClassName: low
  capacity:
    storage: 1Gi
  accessModes: 
  - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/data 
