apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc 
spec:
  storageClassName: low
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
