---
- hosts: dev
  gather_facts: False
  connection: local
  tasks:
    - mail:
        host: smtp.gmail.com
        port: 587
        username: xxxxx
        password: xxxxx
        to: xxxxx
        subject: Test
        subtype: html
        body: "{{ lookup('template', 'templates/mail_body.j2') }}"
        #delegate_to: localhost

