---
- hosts: dev
  tasks:
    - debug: var=ansible_default_ipv4.address
    - debug: var=ansible_nodename
    - name: print dist
      shell: cat /etc/lsb-release | sed -n '2p' | cut -d "=" -f2 
      register: dist
    - name: Print dist
      debug:
        msg: "{{ dist.stdout }}"
    - name: print cpu
      shell: top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}'
      register: cpu
    - name: Print cpu
      debug:
        msg: "{{ cpu.stdout }}"
    - name: print memory
      shell: free -m | sed -n '2p' | awk '{print $3;}'
      register: mem
    - name: Print mem
      debug:
        msg: "{{ mem.stdout }}"
