---
- hosts: dev
  tasks:
    - name: Installs nginx web server
      apt: pkg=nginx state=present update_cache=true
      
    - name: verify nginx user
      shell: cat /etc/nginx/nginx.conf | grep -i www-data | awk '{print $2;}' | sed 's/.$//'
      register:  user
  
    - name: Print nginx user
      debug:
        msg: "nginx user : {{ user.stdout }}"
    
    - name: verify nginx port
      shell: cat /etc/nginx/sites-enabled/default | grep -i 80 | awk '{print $2;}' | sed -n '1p'
      register:  port
    
    - name: Print nginx port
      debug:
        msg: "nginx port : {{ port.stdout }}"   
 
    - name: verify nginx html directory path
      shell: cat /etc/nginx/sites-enabled/default | grep -i /var/www/html | awk '{print $2;}' | sed 's/.$//'
      register:  path
    
    - name: Print nginx path
      debug:
        msg: "nginx path : {{ path.stdout }}"   
  
  handlers:
    - name: start nginx
      service: name=nginx state=started



