---
- name: Test Playbook
  hosts: "{{ nodes }}"
  remote_user: deploy
  become_user: deploy
  become: true
  become_method: sudo
 
  

  tasks:
    - name: Hello server
      shell: echo "hello world" >> /tmp/test.txt

