---
# Update Jenkins so that plugin updates don't fail.
- name: Create update directory
  file:
    path: "{{ jenkins_home }}/updates"
    state: directory
    owner: jenkins
    group: jenkins

- name: Download current plugin updates from Jenkins update site
  get_url:
    url: http://updates.jenkins-ci.org/update-center.json
    dest: "{{ jenkins_home }}/updates/default.json"
    owner: jenkins
    group: jenkins
    mode: 0440

- name: Remove first and last line from json file
  replace:
    path: "{{ jenkins_home }}/updates/default.json"
    regexp: "1d;$d"

- name: Install plugin
  jenkins_plugin:
    name: "{{ item }}"
    url_username: admin
    url_password: admin
    url: http://192.168.10.116:8080
  with_items: "{{ plugins }}"

- name: copy blueocean plugins list
  copy:
    src: /etc/ansible/files/p3.yml
    dest: /opt/apps/plugs/p4.yml
    mode: 777

- name: remove jenkins plugins
  file:
    state: "{{ item }}"
    path: "/var/lib/jenkins/plugins/*.hpi"
  with_items:
    - absent

- copy:
    src: "{{ item }}"
    dest: /var/lib/jenkins/plugins/
    owner: root
    #mode: 600
  with_fileglob:
    - /opt/apps/jenkins/plugins/*

- name: Restart Jenkins if required
  service:
     name: jenkins
     state: restarted
    
