apiVersion: v1
kind: Pod
metadata:
  name: limit-cpu-pod
  labels:
    k8s-app: limit-cpu-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    args:
    - -c
    - touch /data/healthy; sleep 10800
    securityContext:
      runAsUser: 10000
      capabilities:
        drop:
        - KILL
    imagePullPolicy: Always
    volumeMounts:
    - name: data
      mountPath: /data
    livenessProbe:
      exec:
        command:
        - ls
        - /data/healthy
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 1
    resources:
      requests:
        cpu: 750m
  restartPolicy: Always
  volumes:
  - name: data
    emptyDir: {}
