---
# handlers file for search-zookeeper
#- name: Reload systemd
#  command: systemctl daemon-reload

#- name: Restart zookeeper
#  systemd:
#    name: zookeeper
#    state: restarted
#  when: zookeeper_service_state != 'stopped' 
- name: restart zookeeper
  service: name=zookeeper state=restarted
